# Generated by Django 5.0.6 on 2024-05-31 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="User",
        ),
    ]
