# Generated by Django 5.0.6 on 2024-06-13 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_rename_employee_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
