# Generated by Django 5.0.6 on 2024-08-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iso2",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="country",
            name="iso3",
            field=models.CharField(default="", max_length=10),
        ),
    ]
