# Generated by Django 5.0.6 on 2024-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lookups", "0003_alter_country_iso2_alter_country_iso3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="city",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
