# Generated by Django 5.0.6 on 2024-09-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0006_degreesubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="DegreeTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active_status", models.BooleanField(default=True)),
                (
                    "degree_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lookups.degreetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Degree",
                "verbose_name_plural": "Degrees",
            },
        ),
    ]
