# Generated by Django 5.0.6 on 2024-09-16 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0007_degreetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounting_skills",
                        to="lookups.skillcategory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="lookups_acc_id_fe0fe3_idx")
                ],
            },
        ),
    ]
