# Generated by Django 5.0.6 on 2024-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0016_softskills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="skills",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="skills",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skills",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
