# Generated by Django 5.0.6 on 2024-09-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lookups", "0017_skillcategory_created_at_skillcategory_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminsoftware",
            name="category",
        ),
        migrations.RemoveField(
            model_name="advertisingtools",
            name="category",
        ),
        migrations.RemoveField(
            model_name="cms",
            name="category",
        ),
        migrations.RemoveField(
            model_name="communicationskills",
            name="category",
        ),
        migrations.RemoveField(
            model_name="database",
            name="category",
        ),
        migrations.RemoveField(
            model_name="frameworks",
            name="category",
        ),
        migrations.RemoveField(
            model_name="programminglanguage",
            name="category",
        ),
        migrations.RemoveField(
            model_name="softskills",
            name="category",
        ),
        migrations.DeleteModel(
            name="AccountingSkills",
        ),
        migrations.DeleteModel(
            name="AdminSoftware",
        ),
        migrations.DeleteModel(
            name="AdvertisingTools",
        ),
        migrations.DeleteModel(
            name="CMS",
        ),
        migrations.DeleteModel(
            name="CommunicationSkills",
        ),
        migrations.DeleteModel(
            name="Database",
        ),
        migrations.DeleteModel(
            name="Frameworks",
        ),
        migrations.DeleteModel(
            name="ProgrammingLanguage",
        ),
        migrations.DeleteModel(
            name="SoftSkills",
        ),
    ]
