from django.db import models
from .modules.education.models import Education
from .modules.experience.models import *
from .modules.job_profiles.models import *
from .modules.languages.models import *
from .modules.skills.models import *
from .modules.job_seeker.models import *
from .modules.settings.models import *
from .modules.job_assessment.models import *
from .modules.accounts.models import *
from .modules.job_interviews.models import *
