# Generated by Django 5.0.6 on 2024-08-15 11:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("lookups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_rate", models.IntegerField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "ssn_cnic_passport",
                    models.CharField(default=None, max_length=45, null=True),
                ),
                ("state", models.CharField(default=None, max_length=45, null=True)),
                ("city", models.CharField(default=None, max_length=45, null=True)),
                ("address", models.TextField(default=None, null=True)),
                ("reviewed_at", models.CharField(max_length=45)),
                ("rating", models.CharField(max_length=45)),
                ("is_approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="JobTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("reset_token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScreeningInterviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
                ("questions", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("obtained_marks", models.IntegerField(default=0)),
                ("total_marks", models.IntegerField(default=26)),
                ("status", models.CharField(default="Pending", max_length=45)),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="job_seekers.jobprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfilePortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("description", models.TextField()),
                ("tags", models.TextField()),
                ("url", models.CharField(max_length=45)),
                ("files", models.TextField()),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to="job_seekers.jobprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication_rating", models.FloatField()),
                ("experience_rating", models.FloatField()),
                ("education_rating", models.FloatField()),
                ("skills_rating", models.FloatField()),
                ("comments", models.CharField(max_length=45)),
                ("status", models.CharField(max_length=45)),
                ("reject_reason_id", models.IntegerField()),
                ("next_review", models.DateField()),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="job_seekers.jobprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_profile",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile_skills",
                        to="job_seekers.jobprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_profile_skill",
                        to="lookups.skills",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("phone", models.CharField(blank=True, max_length=45)),
                ("father_name", models.CharField(blank=True, max_length=45)),
                ("source_id", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=45)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("id_number", models.CharField(blank=True, max_length=45)),
                ("marital_status", models.CharField(blank=True, max_length=45)),
                ("gender", models.CharField(blank=True, max_length=45)),
                ("profile_picture", models.CharField(blank=True, max_length=45)),
                ("cover_photo", models.CharField(blank=True, max_length=45)),
                ("about", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=45)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="job_seeker_set",
                        related_query_name="job_seeker",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="job_seeker_set",
                        related_query_name="job_seeker",
                        to="auth.permission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("job_type_id", models.CharField(max_length=45)),
                ("company_name", models.CharField(max_length=45)),
                ("start_date", models.DateField()),
                ("currently_working", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=45)),
                ("experience_letter_photo", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobprofile_experiences",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="job_seeker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_profile",
                to="job_seekers.jobseeker",
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("education_type_id", models.CharField(max_length=45)),
                ("major_subjects", models.CharField(max_length=45)),
                ("score", models.CharField(max_length=45)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("institute_name", models.CharField(max_length=45)),
                ("certificate_photo", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Education",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApprovalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_completion_percentage", models.FloatField(default=0)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "job_seeker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="job_title",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_profiles",
                to="job_seekers.jobtitle",
            ),
        ),
        migrations.CreateModel(
            name="JobTitleAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("options", models.JSONField()),
                ("answer", models.CharField(max_length=300)),
                (
                    "job_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="job_seekers.jobtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_id", models.CharField(max_length=45)),
                ("level", models.CharField(max_length=45)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobProfileInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_recording_url", models.CharField(max_length=45)),
                ("result", models.CharField(max_length=45)),
                ("transcription", models.TextField()),
                ("status", models.CharField(max_length=45)),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_seekers.jobprofile",
                    ),
                ),
                (
                    "screening_interview_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_seekers.screeninginterviewtemplate",
                    ),
                ),
            ],
        ),
    ]
