# Generated by Django 5.0.6 on 2024-08-21 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_seekers", "0001_initial"),
        ("lookups", "0005_jobtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprofile",
            name="job_title",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_profiles",
                to="lookups.jobtitle",
            ),
        ),
        migrations.AlterField(
            model_name="jobtitleassessment",
            name="job_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="lookups.jobtitle",
            ),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="country",
            field=models.CharField(default=None, max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name="JobTitle",
        ),
    ]
