# Generated by Django 5.0.6 on 2024-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_alter_jobprofile_job_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="jobprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="jobprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="jobprofile",
            name="ssn_cnic_passport",
        ),
        migrations.RemoveField(
            model_name="jobprofile",
            name="state",
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobprofile",
            name="job_profile_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
