# Generated by Django 5.0.6 on 2024-09-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_seekers",
            "0003_remove_jobprofile_address_remove_jobprofile_city_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprofile",
            name="job_profile_name",
        ),
    ]
