# Generated by Django 5.0.6 on 2024-09-04 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0005_rename_completion_date_education_from_date_and_more"),
        ("lookups", "0007_degreetitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprofileexperience",
            name="experience_letter_photo",
        ),
        migrations.RemoveField(
            model_name="jobprofileexperience",
            name="job_type_id",
        ),
        migrations.RemoveField(
            model_name="jobprofileexperience",
            name="title",
        ),
        migrations.AddField(
            model_name="jobprofileexperience",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="lookups.city",
            ),
        ),
        migrations.AddField(
            model_name="jobprofileexperience",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="lookups.country",
            ),
        ),
        migrations.AddField(
            model_name="jobprofileexperience",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobprofileexperience",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
