# Generated by Django 5.0.6 on 2024-09-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_seekers",
            "0006_remove_jobprofileexperience_experience_letter_photo_and_more",
        ),
        ("lookups", "0007_degreetitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="language_id",
        ),
        migrations.RemoveField(
            model_name="language",
            name="level",
        ),
        migrations.AddField(
            model_name="language",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_seeker_languages",
                to="lookups.language",
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Professional", "Professional"),
                ],
                max_length=45,
                null=True,
            ),
        ),
    ]
