# Generated by Django 5.0.6 on 2024-09-04 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job_seekers",
            "0007_remove_language_language_id_remove_language_level_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="language",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
