# Generated by Django 5.0.6 on 2024-09-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0010_alter_education_discipline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JobProfileExperience",
        ),
    ]
