# Generated by Django 5.0.6 on 2024-09-09 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0011_delete_jobprofileexperience"),
        ("lookups", "0007_degreetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobProfileExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=45)),
                ("start_date", models.DateField()),
                ("currently_working", models.BooleanField(default=False)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=45)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="lookups.city",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="lookups.country",
                    ),
                ),
                (
                    "job_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="job_seekers.jobprofile",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobprofile_experiences",
                        to="job_seekers.jobseeker",
                    ),
                ),
            ],
        ),
    ]
