# Generated by Django 5.0.6 on 2024-09-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0012_jobprofileexperience"),
        ("lookups", "0007_degreetitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseeker",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lookups.city",
            ),
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lookups.state",
            ),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lookups.country",
            ),
        ),
    ]
