# Generated by Django 5.0.6 on 2024-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "job_seekers",
            "0014_alter_jobseeker_options_remove_jobseeker_source_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="jobseeker_set",
                related_query_name="job_seeker",
                to="auth.group",
            ),
        ),
    ]
