# Generated by Django 5.0.6 on 2024-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("job_seekers", "0015_alter_jobseeker_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="jobseeker_permission_set",
                related_query_name="job_seeker",
                to="auth.permission",
            ),
        ),
    ]
