# Generated by Django 5.0.6 on 2024-09-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0018_alter_jobseeker_options_alter_jobseeker_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseeker",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="jobseeker",
            name="user_permissions",
        ),
    ]
