# Generated by Django 5.0.6 on 2024-09-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0019_remove_jobseeker_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprofileexperience",
            name="job_seeker",
        ),
    ]
