# Generated by Django 5.0.6 on 2024-09-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0020_remove_jobprofileexperience_job_seeker"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobprofileexperience",
            name="job_seeker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobprofile_experiences",
                to="job_seekers.jobseeker",
            ),
        ),
    ]
