# Generated by Django 5.0.6 on 2024-09-11 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0021_jobprofileexperience_job_seeker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprofile",
            name="completion_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="jobprofileexperience",
            name="job_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobprofile_experiences",
                to="job_seekers.jobprofile",
            ),
        ),
    ]
