# Generated by Django 5.0.6 on 2024-09-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0022_alter_jobprofile_completion_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobprofile",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_profile",
                to="job_seekers.jobseeker",
            ),
        ),
    ]
