# Generated by Django 5.0.6 on 2024-09-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0023_alter_jobprofile_job_seeker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprofileportfolio",
            name="files",
        ),
        migrations.AddField(
            model_name="jobprofileportfolio",
            name="portfolio_images",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="jobprofileportfolio",
            name="url",
            field=models.CharField(max_length=255),
        ),
    ]
