# Generated by Django 5.0.6 on 2024-09-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0024_remove_jobprofileportfolio_files_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobprofileportfolio",
            old_name="portfolio_images",
            new_name="portfolio_image",
        ),
    ]
