# Generated by Django 5.0.6 on 2024-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0028_alter_jobprofile_completion_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                ],
                max_length=45,
            ),
        ),
    ]
