# Generated by Django 5.0.6 on 2024-09-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0029_alter_jobseeker_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseeker",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
